// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteAssetOKCode is the HTTP code returned for type DeleteAssetOK
const DeleteAssetOKCode int = 200

/*
DeleteAssetOK OK

swagger:response deleteAssetOK
*/
type DeleteAssetOK struct {
}

// NewDeleteAssetOK creates DeleteAssetOK with default headers values
func NewDeleteAssetOK() *DeleteAssetOK {

	return &DeleteAssetOK{}
}

// WriteResponse to the client
func (o *DeleteAssetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteAssetBadRequestCode is the HTTP code returned for type DeleteAssetBadRequest
const DeleteAssetBadRequestCode int = 400

/*
DeleteAssetBadRequest BadRequest

swagger:response deleteAssetBadRequest
*/
type DeleteAssetBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteAssetBadRequest creates DeleteAssetBadRequest with default headers values
func NewDeleteAssetBadRequest() *DeleteAssetBadRequest {

	return &DeleteAssetBadRequest{}
}

// WithPayload adds the payload to the delete asset bad request response
func (o *DeleteAssetBadRequest) WithPayload(payload string) *DeleteAssetBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete asset bad request response
func (o *DeleteAssetBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAssetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
