// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteItemByCodeParams creates a new DeleteItemByCodeParams object
//
// There are no default values defined in the spec.
func NewDeleteItemByCodeParams() DeleteItemByCodeParams {

	return DeleteItemByCodeParams{}
}

// DeleteItemByCodeParams contains all the bound params for the delete item by code operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteItemByCode
type DeleteItemByCodeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Code string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteItemByCodeParams() beforehand.
func (o *DeleteItemByCodeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCode, rhkCode, _ := route.Params.GetOK("code")
	if err := o.bindCode(rCode, rhkCode, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCode binds and validates parameter Code from path.
func (o *DeleteItemByCodeParams) bindCode(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Code = raw

	return nil
}
