// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteItemByCodeOKCode is the HTTP code returned for type DeleteItemByCodeOK
const DeleteItemByCodeOKCode int = 200

/*
DeleteItemByCodeOK OK

swagger:response deleteItemByCodeOK
*/
type DeleteItemByCodeOK struct {
}

// NewDeleteItemByCodeOK creates DeleteItemByCodeOK with default headers values
func NewDeleteItemByCodeOK() *DeleteItemByCodeOK {

	return &DeleteItemByCodeOK{}
}

// WriteResponse to the client
func (o *DeleteItemByCodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteItemByCodeBadRequestCode is the HTTP code returned for type DeleteItemByCodeBadRequest
const DeleteItemByCodeBadRequestCode int = 400

/*
DeleteItemByCodeBadRequest BadRequest

swagger:response deleteItemByCodeBadRequest
*/
type DeleteItemByCodeBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteItemByCodeBadRequest creates DeleteItemByCodeBadRequest with default headers values
func NewDeleteItemByCodeBadRequest() *DeleteItemByCodeBadRequest {

	return &DeleteItemByCodeBadRequest{}
}

// WithPayload adds the payload to the delete item by code bad request response
func (o *DeleteItemByCodeBadRequest) WithPayload(payload string) *DeleteItemByCodeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete item by code bad request response
func (o *DeleteItemByCodeBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteItemByCodeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteItemByCodeNotFoundCode is the HTTP code returned for type DeleteItemByCodeNotFound
const DeleteItemByCodeNotFoundCode int = 404

/*
DeleteItemByCodeNotFound NotFound

swagger:response deleteItemByCodeNotFound
*/
type DeleteItemByCodeNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteItemByCodeNotFound creates DeleteItemByCodeNotFound with default headers values
func NewDeleteItemByCodeNotFound() *DeleteItemByCodeNotFound {

	return &DeleteItemByCodeNotFound{}
}

// WithPayload adds the payload to the delete item by code not found response
func (o *DeleteItemByCodeNotFound) WithPayload(payload string) *DeleteItemByCodeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete item by code not found response
func (o *DeleteItemByCodeNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteItemByCodeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
