// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DownloadAssetOKCode is the HTTP code returned for type DownloadAssetOK
const DownloadAssetOKCode int = 200

/*
DownloadAssetOK OK

swagger:response downloadAssetOK
*/
type DownloadAssetOK struct {
}

// NewDownloadAssetOK creates DownloadAssetOK with default headers values
func NewDownloadAssetOK() *DownloadAssetOK {

	return &DownloadAssetOK{}
}

// WriteResponse to the client
func (o *DownloadAssetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DownloadAssetBadRequestCode is the HTTP code returned for type DownloadAssetBadRequest
const DownloadAssetBadRequestCode int = 400

/*
DownloadAssetBadRequest BadRequest

swagger:response downloadAssetBadRequest
*/
type DownloadAssetBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDownloadAssetBadRequest creates DownloadAssetBadRequest with default headers values
func NewDownloadAssetBadRequest() *DownloadAssetBadRequest {

	return &DownloadAssetBadRequest{}
}

// WithPayload adds the payload to the download asset bad request response
func (o *DownloadAssetBadRequest) WithPayload(payload string) *DownloadAssetBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download asset bad request response
func (o *DownloadAssetBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadAssetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DownloadAssetNotFoundCode is the HTTP code returned for type DownloadAssetNotFound
const DownloadAssetNotFoundCode int = 404

/*
DownloadAssetNotFound NotFound

swagger:response downloadAssetNotFound
*/
type DownloadAssetNotFound struct {
}

// NewDownloadAssetNotFound creates DownloadAssetNotFound with default headers values
func NewDownloadAssetNotFound() *DownloadAssetNotFound {

	return &DownloadAssetNotFound{}
}

// WriteResponse to the client
func (o *DownloadAssetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
