// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetItemByCodeHandlerFunc turns a function with the right signature into a get item by code handler
type GetItemByCodeHandlerFunc func(GetItemByCodeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetItemByCodeHandlerFunc) Handle(params GetItemByCodeParams) middleware.Responder {
	return fn(params)
}

// GetItemByCodeHandler interface for that can handle valid get item by code params
type GetItemByCodeHandler interface {
	Handle(GetItemByCodeParams) middleware.Responder
}

// NewGetItemByCode creates a new http.Handler for the get item by code operation
func NewGetItemByCode(ctx *middleware.Context, handler GetItemByCodeHandler) *GetItemByCode {
	return &GetItemByCode{Context: ctx, Handler: handler}
}

/*
	GetItemByCode swagger:route GET /item/{code} getItemByCode

Get a item or its children
*/
type GetItemByCode struct {
	Context *middleware.Context
	Handler GetItemByCodeHandler
}

func (o *GetItemByCode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetItemByCodeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
