// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/alydnhrealgang/moving/server/models"
)

// GetItemByCodeOKCode is the HTTP code returned for type GetItemByCodeOK
const GetItemByCodeOKCode int = 200

/*
GetItemByCodeOK OK

swagger:response getItemByCodeOK
*/
type GetItemByCodeOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ItemData `json:"body,omitempty"`
}

// NewGetItemByCodeOK creates GetItemByCodeOK with default headers values
func NewGetItemByCodeOK() *GetItemByCodeOK {

	return &GetItemByCodeOK{}
}

// WithPayload adds the payload to the get item by code o k response
func (o *GetItemByCodeOK) WithPayload(payload []*models.ItemData) *GetItemByCodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get item by code o k response
func (o *GetItemByCodeOK) SetPayload(payload []*models.ItemData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemByCodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ItemData, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetItemByCodeBadRequestCode is the HTTP code returned for type GetItemByCodeBadRequest
const GetItemByCodeBadRequestCode int = 400

/*
GetItemByCodeBadRequest BadRequest

swagger:response getItemByCodeBadRequest
*/
type GetItemByCodeBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetItemByCodeBadRequest creates GetItemByCodeBadRequest with default headers values
func NewGetItemByCodeBadRequest() *GetItemByCodeBadRequest {

	return &GetItemByCodeBadRequest{}
}

// WithPayload adds the payload to the get item by code bad request response
func (o *GetItemByCodeBadRequest) WithPayload(payload string) *GetItemByCodeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get item by code bad request response
func (o *GetItemByCodeBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemByCodeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetItemByCodeNotFoundCode is the HTTP code returned for type GetItemByCodeNotFound
const GetItemByCodeNotFoundCode int = 404

/*
GetItemByCodeNotFound NotFound

swagger:response getItemByCodeNotFound
*/
type GetItemByCodeNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetItemByCodeNotFound creates GetItemByCodeNotFound with default headers values
func NewGetItemByCodeNotFound() *GetItemByCodeNotFound {

	return &GetItemByCodeNotFound{}
}

// WithPayload adds the payload to the get item by code not found response
func (o *GetItemByCodeNotFound) WithPayload(payload string) *GetItemByCodeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get item by code not found response
func (o *GetItemByCodeNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemByCodeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
