// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAssetHandlerFunc turns a function with the right signature into a get asset handler
type GetAssetHandlerFunc func(GetAssetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAssetHandlerFunc) Handle(params GetAssetParams) middleware.Responder {
	return fn(params)
}

// GetAssetHandler interface for that can handle valid get asset params
type GetAssetHandler interface {
	Handle(GetAssetParams) middleware.Responder
}

// NewGetAsset creates a new http.Handler for the get asset operation
func NewGetAsset(ctx *middleware.Context, handler GetAssetHandler) *GetAsset {
	return &GetAsset{Context: ctx, Handler: handler}
}

/*
	GetAsset swagger:route GET /assets/{path}/{name} getAsset

Retrieve the metadata of an asset
*/
type GetAsset struct {
	Context *middleware.Context
	Handler GetAssetHandler
}

func (o *GetAsset) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAssetParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
