// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewMovingAPI creates a new Moving instance
func NewMovingAPI(spec *loads.Document) *MovingAPI {
	return &MovingAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		BinConsumer:           runtime.ByteStreamConsumer(),
		JSONConsumer:          runtime.JSONConsumer(),
		MultipartformConsumer: runtime.DiscardConsumer,
		TxtConsumer:           runtime.TextConsumer(),

		JSONProducer: runtime.JSONProducer(),

		DeleteAssetHandler: DeleteAssetHandlerFunc(func(params DeleteAssetParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteAsset has not yet been implemented")
		}),
		DeleteItemByCodeHandler: DeleteItemByCodeHandlerFunc(func(params DeleteItemByCodeParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteItemByCode has not yet been implemented")
		}),
		DownloadAssetHandler: DownloadAssetHandlerFunc(func(params DownloadAssetParams) middleware.Responder {
			return middleware.NotImplemented("operation DownloadAsset has not yet been implemented")
		}),
		GetAssetHandler: GetAssetHandlerFunc(func(params GetAssetParams) middleware.Responder {
			return middleware.NotImplemented("operation GetAsset has not yet been implemented")
		}),
		GetItemByCodeHandler: GetItemByCodeHandlerFunc(func(params GetItemByCodeParams) middleware.Responder {
			return middleware.NotImplemented("operation GetItemByCode has not yet been implemented")
		}),
		MoveItemsHandler: MoveItemsHandlerFunc(func(params MoveItemsParams) middleware.Responder {
			return middleware.NotImplemented("operation MoveItems has not yet been implemented")
		}),
		QueryItemsHandler: QueryItemsHandlerFunc(func(params QueryItemsParams) middleware.Responder {
			return middleware.NotImplemented("operation QueryItems has not yet been implemented")
		}),
		SaveItemHandler: SaveItemHandlerFunc(func(params SaveItemParams) middleware.Responder {
			return middleware.NotImplemented("operation SaveItem has not yet been implemented")
		}),
		SuggestTextsHandler: SuggestTextsHandlerFunc(func(params SuggestTextsParams) middleware.Responder {
			return middleware.NotImplemented("operation SuggestTexts has not yet been implemented")
		}),
		UploadAssetHandler: UploadAssetHandlerFunc(func(params UploadAssetParams) middleware.Responder {
			return middleware.NotImplemented("operation UploadAsset has not yet been implemented")
		}),
	}
}

/*MovingAPI MovingApi */
type MovingAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// BinConsumer registers a consumer for the following mime types:
	//   - application/octet-stream
	//   - image/gif
	//   - image/jpeg
	//   - image/png
	BinConsumer runtime.Consumer
	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer
	// MultipartformConsumer registers a consumer for the following mime types:
	//   - multipart/form-data
	MultipartformConsumer runtime.Consumer
	// TxtConsumer registers a consumer for the following mime types:
	//   - text/plain
	TxtConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// DeleteAssetHandler sets the operation handler for the delete asset operation
	DeleteAssetHandler DeleteAssetHandler
	// DeleteItemByCodeHandler sets the operation handler for the delete item by code operation
	DeleteItemByCodeHandler DeleteItemByCodeHandler
	// DownloadAssetHandler sets the operation handler for the download asset operation
	DownloadAssetHandler DownloadAssetHandler
	// GetAssetHandler sets the operation handler for the get asset operation
	GetAssetHandler GetAssetHandler
	// GetItemByCodeHandler sets the operation handler for the get item by code operation
	GetItemByCodeHandler GetItemByCodeHandler
	// MoveItemsHandler sets the operation handler for the move items operation
	MoveItemsHandler MoveItemsHandler
	// QueryItemsHandler sets the operation handler for the query items operation
	QueryItemsHandler QueryItemsHandler
	// SaveItemHandler sets the operation handler for the save item operation
	SaveItemHandler SaveItemHandler
	// SuggestTextsHandler sets the operation handler for the suggest texts operation
	SuggestTextsHandler SuggestTextsHandler
	// UploadAssetHandler sets the operation handler for the upload asset operation
	UploadAssetHandler UploadAssetHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *MovingAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *MovingAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *MovingAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *MovingAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *MovingAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *MovingAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *MovingAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *MovingAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *MovingAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the MovingAPI
func (o *MovingAPI) Validate() error {
	var unregistered []string

	if o.BinConsumer == nil {
		unregistered = append(unregistered, "BinConsumer")
	}
	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}
	if o.MultipartformConsumer == nil {
		unregistered = append(unregistered, "MultipartformConsumer")
	}
	if o.TxtConsumer == nil {
		unregistered = append(unregistered, "TxtConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.DeleteAssetHandler == nil {
		unregistered = append(unregistered, "DeleteAssetHandler")
	}
	if o.DeleteItemByCodeHandler == nil {
		unregistered = append(unregistered, "DeleteItemByCodeHandler")
	}
	if o.DownloadAssetHandler == nil {
		unregistered = append(unregistered, "DownloadAssetHandler")
	}
	if o.GetAssetHandler == nil {
		unregistered = append(unregistered, "GetAssetHandler")
	}
	if o.GetItemByCodeHandler == nil {
		unregistered = append(unregistered, "GetItemByCodeHandler")
	}
	if o.MoveItemsHandler == nil {
		unregistered = append(unregistered, "MoveItemsHandler")
	}
	if o.QueryItemsHandler == nil {
		unregistered = append(unregistered, "QueryItemsHandler")
	}
	if o.SaveItemHandler == nil {
		unregistered = append(unregistered, "SaveItemHandler")
	}
	if o.SuggestTextsHandler == nil {
		unregistered = append(unregistered, "SuggestTextsHandler")
	}
	if o.UploadAssetHandler == nil {
		unregistered = append(unregistered, "UploadAssetHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *MovingAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *MovingAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *MovingAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *MovingAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/octet-stream":
			result["application/octet-stream"] = o.BinConsumer
		case "image/gif":
			result["image/gif"] = o.BinConsumer
		case "image/jpeg":
			result["image/jpeg"] = o.BinConsumer
		case "image/png":
			result["image/png"] = o.BinConsumer
		case "application/json":
			result["application/json"] = o.JSONConsumer
		case "multipart/form-data":
			result["multipart/form-data"] = o.MultipartformConsumer
		case "text/plain":
			result["text/plain"] = o.TxtConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *MovingAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *MovingAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the moving API
func (o *MovingAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *MovingAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/assets/{path}/{name}"] = NewDeleteAsset(o.context, o.DeleteAssetHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/item/{code}"] = NewDeleteItemByCode(o.context, o.DeleteItemByCodeHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/assets/download/{path}/{name}"] = NewDownloadAsset(o.context, o.DownloadAssetHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/assets/{path}/{name}"] = NewGetAsset(o.context, o.GetAssetHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/item/{code}"] = NewGetItemByCode(o.context, o.GetItemByCodeHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/items/move"] = NewMoveItems(o.context, o.MoveItemsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/items/query"] = NewQueryItems(o.context, o.QueryItemsHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/items"] = NewSaveItem(o.context, o.SaveItemHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/suggest/{name}/{text}"] = NewSuggestTexts(o.context, o.SuggestTextsHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/assets"] = NewUploadAsset(o.context, o.UploadAssetHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *MovingAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *MovingAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *MovingAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *MovingAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *MovingAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
