// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// QueryItemsHandlerFunc turns a function with the right signature into a query items handler
type QueryItemsHandlerFunc func(QueryItemsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn QueryItemsHandlerFunc) Handle(params QueryItemsParams) middleware.Responder {
	return fn(params)
}

// QueryItemsHandler interface for that can handle valid query items params
type QueryItemsHandler interface {
	Handle(QueryItemsParams) middleware.Responder
}

// NewQueryItems creates a new http.Handler for the query items operation
func NewQueryItems(ctx *middleware.Context, handler QueryItemsHandler) *QueryItems {
	return &QueryItems{Context: ctx, Handler: handler}
}

/*
	QueryItems swagger:route GET /items/query queryItems

Query items
*/
type QueryItems struct {
	Context *middleware.Context
	Handler QueryItemsHandler
}

func (o *QueryItems) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewQueryItemsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
