// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SuggestTextsHandlerFunc turns a function with the right signature into a suggest texts handler
type SuggestTextsHandlerFunc func(SuggestTextsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SuggestTextsHandlerFunc) Handle(params SuggestTextsParams) middleware.Responder {
	return fn(params)
}

// SuggestTextsHandler interface for that can handle valid suggest texts params
type SuggestTextsHandler interface {
	Handle(SuggestTextsParams) middleware.Responder
}

// NewSuggestTexts creates a new http.Handler for the suggest texts operation
func NewSuggestTexts(ctx *middleware.Context, handler SuggestTextsHandler) *SuggestTexts {
	return &SuggestTexts{Context: ctx, Handler: handler}
}

/*
	SuggestTexts swagger:route GET /suggest/{name}/{text} suggestTexts

Retrieve a list of texts by given name and text
*/
type SuggestTexts struct {
	Context *middleware.Context
	Handler SuggestTextsHandler
}

func (o *SuggestTexts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSuggestTextsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
