// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDownloadAssetParams creates a new DownloadAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDownloadAssetParams() *DownloadAssetParams {
	return &DownloadAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadAssetParamsWithTimeout creates a new DownloadAssetParams object
// with the ability to set a timeout on a request.
func NewDownloadAssetParamsWithTimeout(timeout time.Duration) *DownloadAssetParams {
	return &DownloadAssetParams{
		timeout: timeout,
	}
}

// NewDownloadAssetParamsWithContext creates a new DownloadAssetParams object
// with the ability to set a context for a request.
func NewDownloadAssetParamsWithContext(ctx context.Context) *DownloadAssetParams {
	return &DownloadAssetParams{
		Context: ctx,
	}
}

// NewDownloadAssetParamsWithHTTPClient creates a new DownloadAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewDownloadAssetParamsWithHTTPClient(client *http.Client) *DownloadAssetParams {
	return &DownloadAssetParams{
		HTTPClient: client,
	}
}

/*
DownloadAssetParams contains all the parameters to send to the API endpoint

	for the download asset operation.

	Typically these are written to a http.Request.
*/
type DownloadAssetParams struct {

	// Name.
	Name string

	// Path.
	Path string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the download asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadAssetParams) WithDefaults() *DownloadAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the download asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the download asset params
func (o *DownloadAssetParams) WithTimeout(timeout time.Duration) *DownloadAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the download asset params
func (o *DownloadAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the download asset params
func (o *DownloadAssetParams) WithContext(ctx context.Context) *DownloadAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the download asset params
func (o *DownloadAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the download asset params
func (o *DownloadAssetParams) WithHTTPClient(client *http.Client) *DownloadAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the download asset params
func (o *DownloadAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the download asset params
func (o *DownloadAssetParams) WithName(name string) *DownloadAssetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the download asset params
func (o *DownloadAssetParams) SetName(name string) {
	o.Name = name
}

// WithPath adds the path to the download asset params
func (o *DownloadAssetParams) WithPath(path string) *DownloadAssetParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the download asset params
func (o *DownloadAssetParams) SetPath(path string) {
	o.Path = path
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param path
	if err := r.SetPathParam("path", o.Path); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
