// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAssetParams creates a new GetAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetParams() *GetAssetParams {
	return &GetAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetParamsWithTimeout creates a new GetAssetParams object
// with the ability to set a timeout on a request.
func NewGetAssetParamsWithTimeout(timeout time.Duration) *GetAssetParams {
	return &GetAssetParams{
		timeout: timeout,
	}
}

// NewGetAssetParamsWithContext creates a new GetAssetParams object
// with the ability to set a context for a request.
func NewGetAssetParamsWithContext(ctx context.Context) *GetAssetParams {
	return &GetAssetParams{
		Context: ctx,
	}
}

// NewGetAssetParamsWithHTTPClient creates a new GetAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetParamsWithHTTPClient(client *http.Client) *GetAssetParams {
	return &GetAssetParams{
		HTTPClient: client,
	}
}

/*
GetAssetParams contains all the parameters to send to the API endpoint

	for the get asset operation.

	Typically these are written to a http.Request.
*/
type GetAssetParams struct {

	/* Name.

	   如果为支持通配*，则获取所有path下的内容
	*/
	Name string

	// Path.
	Path string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetParams) WithDefaults() *GetAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get asset params
func (o *GetAssetParams) WithTimeout(timeout time.Duration) *GetAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get asset params
func (o *GetAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get asset params
func (o *GetAssetParams) WithContext(ctx context.Context) *GetAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get asset params
func (o *GetAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get asset params
func (o *GetAssetParams) WithHTTPClient(client *http.Client) *GetAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get asset params
func (o *GetAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get asset params
func (o *GetAssetParams) WithName(name string) *GetAssetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get asset params
func (o *GetAssetParams) SetName(name string) {
	o.Name = name
}

// WithPath adds the path to the get asset params
func (o *GetAssetParams) WithPath(path string) *GetAssetParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the get asset params
func (o *GetAssetParams) SetPath(path string) {
	o.Path = path
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param path
	if err := r.SetPathParam("path", o.Path); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
