// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetItemByCodeParams creates a new GetItemByCodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetItemByCodeParams() *GetItemByCodeParams {
	return &GetItemByCodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetItemByCodeParamsWithTimeout creates a new GetItemByCodeParams object
// with the ability to set a timeout on a request.
func NewGetItemByCodeParamsWithTimeout(timeout time.Duration) *GetItemByCodeParams {
	return &GetItemByCodeParams{
		timeout: timeout,
	}
}

// NewGetItemByCodeParamsWithContext creates a new GetItemByCodeParams object
// with the ability to set a context for a request.
func NewGetItemByCodeParamsWithContext(ctx context.Context) *GetItemByCodeParams {
	return &GetItemByCodeParams{
		Context: ctx,
	}
}

// NewGetItemByCodeParamsWithHTTPClient creates a new GetItemByCodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetItemByCodeParamsWithHTTPClient(client *http.Client) *GetItemByCodeParams {
	return &GetItemByCodeParams{
		HTTPClient: client,
	}
}

/*
GetItemByCodeParams contains all the parameters to send to the API endpoint

	for the get item by code operation.

	Typically these are written to a http.Request.
*/
type GetItemByCodeParams struct {

	// ChildrenOnly.
	ChildrenOnly bool

	// Code.
	Code string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get item by code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetItemByCodeParams) WithDefaults() *GetItemByCodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get item by code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetItemByCodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get item by code params
func (o *GetItemByCodeParams) WithTimeout(timeout time.Duration) *GetItemByCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get item by code params
func (o *GetItemByCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get item by code params
func (o *GetItemByCodeParams) WithContext(ctx context.Context) *GetItemByCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get item by code params
func (o *GetItemByCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get item by code params
func (o *GetItemByCodeParams) WithHTTPClient(client *http.Client) *GetItemByCodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get item by code params
func (o *GetItemByCodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChildrenOnly adds the childrenOnly to the get item by code params
func (o *GetItemByCodeParams) WithChildrenOnly(childrenOnly bool) *GetItemByCodeParams {
	o.SetChildrenOnly(childrenOnly)
	return o
}

// SetChildrenOnly adds the childrenOnly to the get item by code params
func (o *GetItemByCodeParams) SetChildrenOnly(childrenOnly bool) {
	o.ChildrenOnly = childrenOnly
}

// WithCode adds the code to the get item by code params
func (o *GetItemByCodeParams) WithCode(code string) *GetItemByCodeParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the get item by code params
func (o *GetItemByCodeParams) SetCode(code string) {
	o.Code = code
}

// WriteToRequest writes these params to a swagger request
func (o *GetItemByCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param childrenOnly
	qrChildrenOnly := o.ChildrenOnly
	qChildrenOnly := swag.FormatBool(qrChildrenOnly)
	if qChildrenOnly != "" {

		if err := r.SetQueryParam("childrenOnly", qChildrenOnly); err != nil {
			return err
		}
	}

	// path param code
	if err := r.SetPathParam("code", o.Code); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
