// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/alydnhrealgang/moving/cli/api/models"
)

// QueryItemsReader is a Reader for the QueryItems structure.
type QueryItemsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryItemsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryItemsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewQueryItemsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewQueryItemsOK creates a QueryItemsOK with default headers values
func NewQueryItemsOK() *QueryItemsOK {
	return &QueryItemsOK{}
}

/*
QueryItemsOK describes a response with status code 200, with default header values.

OK
*/
type QueryItemsOK struct {
	Payload []*models.ItemData
}

// IsSuccess returns true when this query items o k response has a 2xx status code
func (o *QueryItemsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this query items o k response has a 3xx status code
func (o *QueryItemsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query items o k response has a 4xx status code
func (o *QueryItemsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this query items o k response has a 5xx status code
func (o *QueryItemsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this query items o k response a status code equal to that given
func (o *QueryItemsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the query items o k response
func (o *QueryItemsOK) Code() int {
	return 200
}

func (o *QueryItemsOK) Error() string {
	return fmt.Sprintf("[GET /items/query][%d] queryItemsOK  %+v", 200, o.Payload)
}

func (o *QueryItemsOK) String() string {
	return fmt.Sprintf("[GET /items/query][%d] queryItemsOK  %+v", 200, o.Payload)
}

func (o *QueryItemsOK) GetPayload() []*models.ItemData {
	return o.Payload
}

func (o *QueryItemsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryItemsBadRequest creates a QueryItemsBadRequest with default headers values
func NewQueryItemsBadRequest() *QueryItemsBadRequest {
	return &QueryItemsBadRequest{}
}

/*
QueryItemsBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type QueryItemsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this query items bad request response has a 2xx status code
func (o *QueryItemsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this query items bad request response has a 3xx status code
func (o *QueryItemsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query items bad request response has a 4xx status code
func (o *QueryItemsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this query items bad request response has a 5xx status code
func (o *QueryItemsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this query items bad request response a status code equal to that given
func (o *QueryItemsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the query items bad request response
func (o *QueryItemsBadRequest) Code() int {
	return 400
}

func (o *QueryItemsBadRequest) Error() string {
	return fmt.Sprintf("[GET /items/query][%d] queryItemsBadRequest  %+v", 400, o.Payload)
}

func (o *QueryItemsBadRequest) String() string {
	return fmt.Sprintf("[GET /items/query][%d] queryItemsBadRequest  %+v", 400, o.Payload)
}

func (o *QueryItemsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *QueryItemsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
