// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SuggestTextsReader is a Reader for the SuggestTexts structure.
type SuggestTextsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SuggestTextsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSuggestTextsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSuggestTextsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSuggestTextsOK creates a SuggestTextsOK with default headers values
func NewSuggestTextsOK() *SuggestTextsOK {
	return &SuggestTextsOK{}
}

/*
SuggestTextsOK describes a response with status code 200, with default header values.

OK
*/
type SuggestTextsOK struct {
	Payload []string
}

// IsSuccess returns true when this suggest texts o k response has a 2xx status code
func (o *SuggestTextsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this suggest texts o k response has a 3xx status code
func (o *SuggestTextsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this suggest texts o k response has a 4xx status code
func (o *SuggestTextsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this suggest texts o k response has a 5xx status code
func (o *SuggestTextsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this suggest texts o k response a status code equal to that given
func (o *SuggestTextsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the suggest texts o k response
func (o *SuggestTextsOK) Code() int {
	return 200
}

func (o *SuggestTextsOK) Error() string {
	return fmt.Sprintf("[GET /suggest/{name}/{text}][%d] suggestTextsOK  %+v", 200, o.Payload)
}

func (o *SuggestTextsOK) String() string {
	return fmt.Sprintf("[GET /suggest/{name}/{text}][%d] suggestTextsOK  %+v", 200, o.Payload)
}

func (o *SuggestTextsOK) GetPayload() []string {
	return o.Payload
}

func (o *SuggestTextsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSuggestTextsBadRequest creates a SuggestTextsBadRequest with default headers values
func NewSuggestTextsBadRequest() *SuggestTextsBadRequest {
	return &SuggestTextsBadRequest{}
}

/*
SuggestTextsBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type SuggestTextsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this suggest texts bad request response has a 2xx status code
func (o *SuggestTextsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this suggest texts bad request response has a 3xx status code
func (o *SuggestTextsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this suggest texts bad request response has a 4xx status code
func (o *SuggestTextsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this suggest texts bad request response has a 5xx status code
func (o *SuggestTextsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this suggest texts bad request response a status code equal to that given
func (o *SuggestTextsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the suggest texts bad request response
func (o *SuggestTextsBadRequest) Code() int {
	return 400
}

func (o *SuggestTextsBadRequest) Error() string {
	return fmt.Sprintf("[GET /suggest/{name}/{text}][%d] suggestTextsBadRequest  %+v", 400, o.Payload)
}

func (o *SuggestTextsBadRequest) String() string {
	return fmt.Sprintf("[GET /suggest/{name}/{text}][%d] suggestTextsBadRequest  %+v", 400, o.Payload)
}

func (o *SuggestTextsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SuggestTextsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
