// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/alydnhrealgang/moving/cli/api/models"
)

// UploadAssetReader is a Reader for the UploadAsset structure.
type UploadAssetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadAssetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUploadAssetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUploadAssetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUploadAssetOK creates a UploadAssetOK with default headers values
func NewUploadAssetOK() *UploadAssetOK {
	return &UploadAssetOK{}
}

/*
UploadAssetOK describes a response with status code 200, with default header values.

OK
*/
type UploadAssetOK struct {
	Payload *models.AssetDataResponse
}

// IsSuccess returns true when this upload asset o k response has a 2xx status code
func (o *UploadAssetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this upload asset o k response has a 3xx status code
func (o *UploadAssetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload asset o k response has a 4xx status code
func (o *UploadAssetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload asset o k response has a 5xx status code
func (o *UploadAssetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this upload asset o k response a status code equal to that given
func (o *UploadAssetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the upload asset o k response
func (o *UploadAssetOK) Code() int {
	return 200
}

func (o *UploadAssetOK) Error() string {
	return fmt.Sprintf("[POST /assets][%d] uploadAssetOK  %+v", 200, o.Payload)
}

func (o *UploadAssetOK) String() string {
	return fmt.Sprintf("[POST /assets][%d] uploadAssetOK  %+v", 200, o.Payload)
}

func (o *UploadAssetOK) GetPayload() *models.AssetDataResponse {
	return o.Payload
}

func (o *UploadAssetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssetDataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUploadAssetBadRequest creates a UploadAssetBadRequest with default headers values
func NewUploadAssetBadRequest() *UploadAssetBadRequest {
	return &UploadAssetBadRequest{}
}

/*
UploadAssetBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type UploadAssetBadRequest struct {
	Payload string
}

// IsSuccess returns true when this upload asset bad request response has a 2xx status code
func (o *UploadAssetBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload asset bad request response has a 3xx status code
func (o *UploadAssetBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload asset bad request response has a 4xx status code
func (o *UploadAssetBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this upload asset bad request response has a 5xx status code
func (o *UploadAssetBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this upload asset bad request response a status code equal to that given
func (o *UploadAssetBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the upload asset bad request response
func (o *UploadAssetBadRequest) Code() int {
	return 400
}

func (o *UploadAssetBadRequest) Error() string {
	return fmt.Sprintf("[POST /assets][%d] uploadAssetBadRequest  %+v", 400, o.Payload)
}

func (o *UploadAssetBadRequest) String() string {
	return fmt.Sprintf("[POST /assets][%d] uploadAssetBadRequest  %+v", 400, o.Payload)
}

func (o *UploadAssetBadRequest) GetPayload() string {
	return o.Payload
}

func (o *UploadAssetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
