// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AssetData asset data
//
// swagger:model AssetData
type AssetData struct {

	// content type
	ContentType string `json:"contentType,omitempty"`

	// last modified
	LastModified string `json:"lastModified,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`
}

// Validate validates this asset data
func (m *AssetData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this asset data based on context it is used
func (m *AssetData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AssetData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssetData) UnmarshalBinary(b []byte) error {
	var res AssetData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
