// Code generated by go-swagger; DO NOT EDIT.

// Package restapi MovingApi
//
//	MovingApi
//	Schemes:
//	  http
//	Host: 0.0.0.0:8081
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/octet-stream
//	  - image/gif
//	  - image/jpeg
//	  - image/png
//	  - application/json
//	  - multipart/form-data
//	  - text/plain
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
