// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "MovingApi",
    "title": "MovingApi",
    "version": "1.0.0"
  },
  "host": "0.0.0.0:8081",
  "basePath": "/v1",
  "paths": {
    "/assets": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Upload an asset",
        "operationId": "UploadAsset",
        "parameters": [
          {
            "type": "string",
            "name": "path",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "name",
            "in": "formData",
            "required": true
          },
          {
            "type": "file",
            "name": "file",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "contentType",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AssetDataResponse"
            }
          },
          "400": {
            "description": "BadRequest",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/assets/download/{path}/{name}": {
      "get": {
        "consumes": [
          "application/json",
          "image/jpeg",
          "image/png",
          "image/gif",
          "text/plain",
          "application/octet-stream"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Download an asset",
        "operationId": "DownloadAsset",
        "parameters": [
          {
            "type": "string",
            "name": "path",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "BadRequest",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "NotFound"
          }
        }
      }
    },
    "/assets/{path}/{name}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Retrieve the metadata of an asset",
        "operationId": "GetAsset",
        "parameters": [
          {
            "type": "string",
            "name": "path",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "如果为支持通配*，则获取所有path下的内容",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/AssetData"
              }
            }
          },
          "400": {
            "description": "BadRequest",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "NotFound"
          }
        }
      }
    }
  },
  "definitions": {
    "AssetData": {
      "type": "object",
      "properties": {
        "contentType": {
          "type": "string"
        },
        "lastModified": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "size": {
          "type": "integer"
        }
      }
    },
    "AssetDataResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "default": 0
        },
        "data": {
          "type": "object",
          "$ref": "#/definitions/AssetData"
        },
        "messages": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "MovingApi",
    "title": "MovingApi",
    "version": "1.0.0"
  },
  "host": "0.0.0.0:8081",
  "basePath": "/v1",
  "paths": {
    "/assets": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Upload an asset",
        "operationId": "UploadAsset",
        "parameters": [
          {
            "type": "string",
            "name": "path",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "name",
            "in": "formData",
            "required": true
          },
          {
            "type": "file",
            "name": "file",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "contentType",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AssetDataResponse"
            }
          },
          "400": {
            "description": "BadRequest",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/assets/download/{path}/{name}": {
      "get": {
        "consumes": [
          "application/json",
          "application/octet-stream",
          "image/gif",
          "image/jpeg",
          "image/png",
          "text/plain"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Download an asset",
        "operationId": "DownloadAsset",
        "parameters": [
          {
            "type": "string",
            "name": "path",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "BadRequest",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "NotFound"
          }
        }
      }
    },
    "/assets/{path}/{name}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Retrieve the metadata of an asset",
        "operationId": "GetAsset",
        "parameters": [
          {
            "type": "string",
            "name": "path",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "如果为支持通配*，则获取所有path下的内容",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/AssetData"
              }
            }
          },
          "400": {
            "description": "BadRequest",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "NotFound"
          }
        }
      }
    }
  },
  "definitions": {
    "AssetData": {
      "type": "object",
      "properties": {
        "contentType": {
          "type": "string"
        },
        "lastModified": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "size": {
          "type": "integer"
        }
      }
    },
    "AssetDataResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "default": 0
        },
        "data": {
          "type": "object",
          "$ref": "#/definitions/AssetData"
        },
        "messages": {
          "type": "string"
        }
      }
    }
  }
}`))
}
